name: CI -> Deploy to My website
on:
  push:
    branches: [ master, Development ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Here is the deployment action
      - name: Upload from public_html via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: "./public_html"
          delete: "false"


on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to ftp server
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check pull request
        uses: actions/github-script@v3
        id: set-result
        with:
          script: |
            return github.pulls.listFiles({owner: context.payload.repository.owner.login, repo: context.payload.repository.name, pull_number: context.payload.number})
              .then(resp => 
                resp.data.map(
                  file => ({filename: file.filename, status: file.status})
                )
              )
      - name: Upload files to ftp server
        uses: ./ 
        id: upload-to-ftp
        with:
          files: ${{steps.set-result.outputs.result}}
          ftpUsername: ${{ secrets.FTP_USERNAME }}
          ftpPassword: ${{ secrets.FTP_PASSWORD }}
          ftpHostname: ${{ secrets.FTP_SERVER }}
          src: test_folder
          dest: '/test_dir'
